// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api.Models;

public partial class Account
{
    /// <summary>
    /// Account unique identificator
    /// </summary>
    public long AccountId { get; set; }

    /// <summary>
    /// User unique identificator with reference to User table
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// User defined account name
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// User selected Icon type (Font Awesome icon type)
    /// </summary>
    public string Icon { get; set; }

    /// <summary>
    /// Money count on the account at the account creation moment
    /// </summary>
    public decimal InitialBalance { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual User User { get; set; }
}