// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api.Models;

public partial class AuditLog
{
    /// <summary>
    /// Log unique identificator
    /// </summary>
    public long LogId { get; set; }

    /// <summary>
    /// Log creation DateTime
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Log text
    /// </summary>
    public string Action { get; set; }

    public byte[] Timespam { get; set; }

    public string IpAdress { get; set; }

    public virtual User User { get; set; }
}