// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api.Models;

public partial class CategoryType
{
    /// <summary>
    /// CategoryType unique identificator
    /// </summary>
    public byte CategoryTypeId { get; set; }

    /// <summary>
    /// CategoryType Name
    /// </summary>
    public string Name { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}