// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api.Models;

public partial class Category
{
    /// <summary>
    /// Category unique identification
    /// </summary>
    public long CategoryId { get; set; }

    /// <summary>
    /// User unique identification with reference to User table
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// User defined category name
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Category type with reference to CategoryType table
    /// </summary>
    public byte Type { get; set; }

    /// <summary>
    /// User selected Icon type (Font Awesome icon type)
    /// </summary>
    public string Icon { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual CategoryType TypeNavigation { get; set; }

    public virtual User User { get; set; }
}