// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api.Models;

public partial class User
{
    /// <summary>
    /// User unique identificator
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// User Email, uniqe value
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// Password Hash
    /// </summary>
    public byte[] PasswordHash { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}