// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace web_api.Migrations
{
    /// <inheritdoc />
    public partial class AddCategoryTypeRecords : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "CategoryType",
                columns: new[] { "CategoryTypeId", "Name" },
                values: new object[,]
                {
                    { 1, "Income" },
                    { 2, "Expense" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "CategoryType",
                keyColumn: "CategoryTypeId",
                keyValues: new object[] { 1 });

            migrationBuilder.DeleteData(
                table: "CategoryType",
                keyColumn: "CategoryTypeId",
                keyValues: new object[] { 2 });
        }
    }
}
